site_name: Manith's  Notes
site_url: https://manith-ratnayake.github.io/Notes
use_directory_urls: true

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: 
  favicon: 

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange


copyright: Copyright &copy; 2024 Manith Ratnayake



deploy:
  target: main:docs